---
- name: Wait until VM boot
  hosts: vm
  gather_facts: false
  tasks:
    - name: Wait for connection
      wait_for_connection:
    - name: Update apt cache
      become: true
      apt:
        name: iputils-ping
        state: present
        update_cache: true