---
- name: Create config directory
  delegate_to: "{{ hypervisor }}"
  become: true
  file:
    path: /tmp/{{ inventory_hostname }}_config
    state: directory
    mode: '0644'

- name: Write user-data
  delegate_to: "{{ hypervisor }}"
  become: true
  copy:
    content: ""
    dest: /tmp/{{ inventory_hostname }}_config/user-data
    mode: '0644'
  notify: regenerate iso

- name: Write meta-data
  delegate_to: "{{ hypervisor }}"
  become: true
  copy:
    content: |
      instance-id: '{{ uuid }}'
      hostname: '{{ inventory_hostname }}'
      local-hostname: '{{ inventory_hostname }}'
      public-keys:
        - |
          {{ public_key }}
    dest: /tmp/{{ inventory_hostname }}_config/meta-data
    mode: '0644'
  notify: regenerate iso
